# Generated by Django 4.1.1 on 2022-09-21 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_subscription_player_alter_subscription_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.player'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.team'),
        ),
    ]
